name: Flutter Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Analyze & Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Read Flutter version
        id: fvm
        run: |
          FLUTTER_VERSION=$(jq -r '.flutter' .fvmrc)
          echo "flutter_version=$FLUTTER_VERSION" >> $GITHUB_OUTPUT
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ steps.fvm.outputs.flutter_version }}
          cache: true
      - name: Cache pub packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.pub-cache
          key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: |
            ${{ runner.os }}-pub-
      - name: Install dependencies
        run: flutter pub get
      - name: Run flutter doctor
        run: flutter doctor -v
      - name: Run analyze
        run: flutter analyze
      - name: Run tests
        run: flutter test
      - name: Upload golden failure images
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: golden-failures
          path: test/golden/failures
