name: Flutter Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Read Flutter version
        id: fvm
        run: |
          FLUTTER_VERSION=$(jq -r '.flutter' .fvmrc)
          echo "flutter_version=$FLUTTER_VERSION" >> $GITHUB_OUTPUT

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ steps.fvm.outputs.flutter_version }}
          cache: true
      - name: Install dependencies
        run: flutter pub get
      - name: Run tests
        run: flutter test
